---
 okd:
  hosts: bastion
  vars: 
     ansible_port: '22'
     ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
     ansible_ssh_private_key_file: "id_key"
     #ansible_ssh_common_args: "-o IdentitiesOnly=yes"
     ansible_ssh_user: 'vagrant'

